my_string = input('Напишите произвольный текст: ')
print("Количество введенных символов в строке: ", len(my_string))
print('ВЕРХНИЙ РЕГИСТР: ', my_string.upper())
print('нижний регистр: ', my_string.lower())
my_string.replace(' ', '')
print('Первый символ строки: ', my_string[0])
print('Последний символ строки: ', my_string[-1])