my_string = input('Укажите город Вашего проживаниия: ')
print("Количество введенных символов в строке: ", len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])